Alt_$: 0
BankMax: 10000
BankInfo: https://www.almasryalyoum.com/news/details/2791816
BankRate_%: 10
Base: EGP
Conversion: "<a href=\"http://www.floatrates.com/json-feeds.html\">RATES</a>"
Currencies: "<a href=\"https://www.iban.com/currency-codes\">IBAN</a>"
"F8Mode": Ask
INT: USD
"IntFees_%": 0
"LocalFees": 0
"LocalFees_%": 14
Overhead: "<a href=\"https://www.ugotbox.com/help/\">UGOTBOX</a>"
Regions: EGP,USD,SAR,AED,EUR,CNY,JPY,INR
Shipping_$: 50
Traveler_$: 100